### ISSUE TITLE
Problem with Instructions for Building BSP for Apollo Lake

### ISSUE THREAD

**Issue by cdwhite77** [intel/iotg_tsn_ref_sw#1]
Hello,

I am trying to build the Apollo Lake BSP, and the instructions seem to be wrong. I am referring to iotg_tsn_ref_sw-userguide-20190131/TSN_UG/index.htm, section _Step 1: Prepare the Host Machine and Build the BSP_. I have successfully setup the host build machine, cloned the iotg-yocto-bsp-public git repo, and ran the setup.sh script.

There seems to be two problems with the instructions in this section:
1. There is no E3900-MR4-PREEMPT-RT branch/tag to checkout
2. The line, "When prompted to build a custom image, select core-image-rt-tsn-sdk." We do not get prompted to "build a custom image," and when setup.sh does present targets, "core-image-rt-tsn-sdk" is not included in the list.

Thanks,
Chris

**Comment by vincentxw** [comment]
Hi there,

Sorry, i  did not realize there were 2 issues as they were of the same title. As mentioned in the other issue, the name of the BSP tag changed prior to the release. We've updated this in our documentation in a very recent commit. The BSP tag you should be checking out is MR4rt-B-01. Once you've checked that out, the build steps should be similar to the UG.

Thanks!
