### ISSUE TITLE
 double free detected in tcache 2

### ISSUE THREAD

**Issue by ermin-sakic** [intel/iotg_tsn_ref_sw#11]
I am trying to run the taprio example with 5.4.0-25-generic kernel on the recent Ubuntu 20.04 LTS.

After minimal adaption of sample-app-taprio.c to include `sock_txtime` and `txtime_flags` from more recent `/usr/include/linux/net_tstamp.h`, I am facing the double free error when starting the receiver:

```bash
➜  sample-app-taprio git:(apollolake-i) ✗ sudo ./sample-app-taprio -i ens2 -x 2 -q "5 3" -y 3
free(): double free detected in tcache 2
```

Sender seems to start fine.

Are you planning to maintain the repository in future and evaluate against updated linux headers?

**Comment by Huahuasun** [comment]
see the file sample-app-1.c, there is a free function called, delete it. remake the file

**Comment by Huahuasun** [comment]
By the way, My computer can not find the command daenon_cl, Do you know why?

**Comment by vincentxw** [comment]
You can install it from this repo: https://github.com/Avnu/gptp

**Comment by Huahuasun** [comment]
Wowww! Thank you very much！

**Comment by Huahuasun** [comment]
I'm very sorry to bother you, I still have a question, In this demo, I have seen the shell, It uses the command: $daemon_cl enp1s0 -S -D 0,0,0,0, The repo you gived is an executable file, To excute it, I should run this command: $./daemon_cl <interface-name>.
Should I use this command: $./daemon_cl enp1s0 -S -D 0,0,0,0 to achieve the effect in this demo, Thank u very much!

**Comment by vincentxw** [comment]
The difference is just whether you've installed daemon_cl to your /usr/bin. Either way works. 

Thanks for the assist above, i'm closing this issue as there's a resolution via code change. We (maintainers) have no intention to modify apollolake-i branch any more. If any one wants to submit a MR. Go ahead and we'll work to merge it in.

**Comment by liing0228** [comment]
> I am trying to run the taprio example with 5.4.0-25-generic kernel on the recent Ubuntu 20.04 LTS.
> 
> After minimal adaption of sample-app-taprio.c to include `sock_txtime` and `txtime_flags` from more recent `/usr/include/linux/net_tstamp.h`, I am facing the double free error when starting the receiver:
> 
> ```shell
> ➜  sample-app-taprio git:(apollolake-i) ✗ sudo ./sample-app-taprio -i ens2 -x 2 -q "5 3" -y 3
> free(): double free detected in tcache 2
> ```
> 
> Sender seems to start fine.
> 
> Are you planning to maintain the repository in future and evaluate against updated linux headers?

how did you solve the problem ?
can you told me please?

**Comment by Huahuasun** [comment]
> > I am trying to run the taprio example with 5.4.0-25-generic kernel on the recent Ubuntu 20.04 LTS.
> > After minimal adaption of sample-app-taprio.c to include `sock_txtime` and `txtime_flags` from more recent `/usr/include/linux/net_tstamp.h`, I am facing the double free error when starting the receiver:
> > ```shell
> > ➜  sample-app-taprio git:(apollolake-i) ✗ sudo ./sample-app-taprio -i ens2 -x 2 -q "5 3" -y 3
> > free(): double free detected in tcache 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sender seems to start fine.
> > Are you planning to maintain the repository in future and evaluate against updated linux headers?
> 
> how did you solve the problem ? can you told me please?

You can open  the file sample-app-1.c, there is a free function (you can find it by search "free") called, delete it. then remake the file.
