### ISSUE TITLE
Where can i find the i210 tsn driver source code?

### ISSUE THREAD

**Issue by nwpucong** [intel/iotg_tsn_ref_sw#13]
Hello, 
After i followed the TSN_UG_index.htm, run the setup.sh and create a usb flash drive from <yocto-image.hddimg>. I wonder how the i210 tsn driver  implements, but i can't find anything on yocto_build/ useful for that. Does the i210 tsn driver implementation Confidential  ?

**Comment by nwpucong** [comment]
Finally  I find the drivers at  ../kernel-source/drivers/net/ethernet/intel/ .   Those files have no "tsn"  words,  with confuse me at first.

**Comment by vincentxw** [comment]
Hi, glad you found it. 

Just to clarify in case this comes up again. The [Yocto BSP ](https://github.com/intel/iotg_tsn_ref_sw/blob/apollolake-i/doc/DEPENDENCIES.md) specified by this project pulls a specific linux kernel version when building the image and applies 1 out-of-tree patch per the recipe. The linux kernel and i210 (igb) driver are open source.

Quoting the Yocto BSP README: 

> Intel Atom E3900 BSP utilize linux-intel kernel from Intel Github which is hosted in [Intel Github repositories](https://github.com/intel/linux-intel-lts). The branch for Intel Atom E3900 BSP kernel is 4.14/preempt-rt.
