### ISSUE TITLE
Why after Priority 7 setting etf , ptp4l works abnormally?

### ISSUE THREAD

**Issue by nwpucong** [intel/iotg_tsn_ref_sw#14]
I've got a switch with PTP clock enable as master, and connected it with  two I210 devices as slave. I want to run "IEEE 802.1Qbv Demo 3  Scenario 3 Time-Aware Traffic Scheduling and LaunchTime Enabled".
I changed  file "setup_generic.sh"  line 31 without "egress=qos-map 7:7", because i want to run ptp4l without VLAN, so this setup is redundant.  I also changed Step 3 [Board A] "$ ./setup_sync.sh -i enp1s0.3 -b boardA" to "$ ./setup_sync.sh -i enp1s0 -b boardB", so  both I210 device work as PTP slave.   Before Step 10,  the ptp4l on BoardA and BoardB  works good after Step 9 "python scheduler.py -i enp1s0 -q queue-s3-s4.cfg -e 120 -g gate-s2s3.sched", and I got the correct test for rest steps.

Strange things happened when i wanted to do the test second time. But I changed the file "queue-s3s4.cfg"  like below:
5 0 etf 5000000           ---------------->                               7 0 etf 5000000
3 1 etf 5000000                  ----------------> 6 1 etf 5000000
7 2                            ---------------->                                   5 2 

Before step 9 , ptp4l on boardA worked well, but  after this step,  ptp4l worked abnormally, so i could not do following steps. It happened like this:

ptp4l[1487.416]: rms 19 max 37 freq -10141 +/- 17 delay 198 +/- 0
ptp4l[1488.416]: rms 25 max 62 frep -10167 +/- 33 
ptp4l[1489.338]: port 1: link down
ptp4l[1489.338]: port 1: SLAVE to FAULTY on FAULT_DETECTED(FT_UNSPECIFIED)
ptp4l[1489.362]: select local clock a0369f.fffe.628d62 as best master
ptp4l[1489.362]: assuming the grand master role
ptp4l[1489.362]: port 1: master state recommended in slave only mode 
ptp4l[1489.362]: port 1: defaultDs.priority1 probably misconfigured
ptp4l[1491.056]: port 1: link up
ptp4l[1491.078]: port 1: FAULTY to LISTENING on INIT_COMPLETE
ptp4l[1491.162]: port 1: new foreign master 010203.0405.060708-9
ptp4l[1491.411]: select best master clock 010203.0405.060708
ptp4l[1491.411]: updating UTC offset to 0
ptp4l[1491.411]: port 1: LISTENING to UNCALIBRATED on RS_SLAVE
ptp4l[1492.028]: send failed: 105 No buffer space available
ptp4l[1492.028]: port1: send delay request failed
ptp4l[1492.028]: port1: UNCALIBRATED to FAULTY on FAULT_DETECTED(FT_UNSPECIFIED)
ptp4l[1508.076]: port 1: FAULTY to LISTENING on INIT_COMPLETE
ptp4l[1508.161]: port 1: new foreign master 010203.0405.060708-9
ptp4l[1508.411]: select best master clock 010203.0405.060708
ptp4l[1508.411]: updating UTC offset to 0
ptp4l[1508.411]: port 1: LISTENING to UNCALIBRATED on RS_SLAVE
ptp4l[1508.910]: send failed: 105 No buffer space available
ptp4l[1508.910]: port1: send delay request failed
ptp4l[1508.910]: port1: UNCALIBRATED to FAULTY on FAULT_DETECTED(FT_UNSPECIFIED)
...
I tried several times later,  and find that  when "ETF" was set on priority 7,  ptp4l can't work normaly. I  run such tests from USB flashs which were made from core-image-rt-tsn-sdk-intel-corei7-64-20200630234202.hddimg.

**Comment by vincentxw** [comment]
ETF queues can ONLY transmit traffic if the launchtime is specified. Only specific applications that have SO_TXTIME can transmit over ETF queues. PTP4L is not one of them as it doesn't require launchtime to perform time sync. Just use a different/regular queue for ptp4l.
