### ISSUE TITLE
Problem about hardwares

### ISSUE THREAD

**Issue by C0cytus** [intel/iotg_tsn_ref_sw#15]
Hello，

I'm a student learning about TSN. I want to run the project on my raspberry pi (4B+). I have succesfully built it on Ubuntu-20.10- Server. However,  the pi don't support hardware timestamp so i can't run it. The supported hardwares mentioned in the Compatibility  are cpus and NIC. Is there any platform like raspberry pi  for beginners to test the project?

Thanks!

**Comment by vincentxw** [comment]
A commercially available NIC with _some_ TSN support is the Intel I210, which has IEEE 802.1As aka PTP support, as it utilizes hardware timestamping.  So you can get a i210 PCIE card with PTP support (mind the specific model) or a development board like [this](https://www.aaeon.com/en/p/iot-gateway-maker-boards-up-squared). This however will work with the apollolake-i branch only.
