### ISSUE TITLE
Problem with package build "open62541-iotg"

### ISSUE THREAD

**Issue by HomeLH** [intel/iotg_tsn_ref_sw#16]
Hardware: intel up2 , cpu N***
System: Ubuntu 20.04
```
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libelf... yes
checking for libbpf... yes
checking for libjson... yes
checking for open62451... no
configure: error: Package requirements (open62541-iotg) were not met:

No package 'open62541-iotg' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables open62451_CFLAGS
and open62451_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Configure failed
```
I try to install the open62541, but still failed.
```
sudo add-apt-repository ppa:open62541-team/ppa
sudo apt-get update
sudo apt-get install libopen62541-1-dev
```
I want to know how to compile the open62541-iotg package.

**Comment by HomeLH** [comment]
I build open62541-iotg through git patch, but I meet another build error..
```

user@user-AIOT-AIVD:~/iotg_tsn_ref_sw-master$ ./build.sh
configure.ac:3: installing './compile'
configure.ac:2: installing './install-sh'
configure.ac:2: installing './missing'
Makefile.am: installing './depcomp'
configure: WARNING: unrecognized options: --with-open62541-headers
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libelf... yes
checking for libbpf... yes
checking for libjson... yes
checking for open62451... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
configure: WARNING: unrecognized options: --with-open62541-headers
make  all-am
make[1]: Entering directory '/home/user/iotg_tsn_ref_sw-master'
depbase=`echo src/tsq.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.  -O2 -g -fstack-protector-strong -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wformat-overflow -Wno-parentheses -Wno-missing-field-initializers -Wextra -Wall -I/usr/local/include/open62541-iotg -I/usr/include/json-c     -g -O2 -MT src/tsq.o -MD -MP -MF $depbase.Tpo -c -o src/tsq.o src/tsq.c &&\
mv -f $depbase.Tpo $depbase.Po
gcc  -g -O2 -Wl,-z,noexecstack,-z,relro,-z,now -pie  -o tsq src/tsq.o
depbase=`echo src/txrx.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.  -O2 -g -fstack-protector-strong -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wformat-overflow -Wno-parentheses -Wno-missing-field-initializers -Wextra -Wall -I/usr/local/include/open62541-iotg -I/usr/include/json-c     -g -O2 -MT src/txrx.o -MD -MP -MF $depbase.Tpo -c -o src/txrx.o src/txrx.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/txrx-afpkt.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.  -O2 -g -fstack-protector-strong -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wformat-overflow -Wno-parentheses -Wno-missing-field-initializers -Wextra -Wall -I/usr/local/include/open62541-iotg -I/usr/include/json-c     -g -O2 -MT src/txrx-afpkt.o -MD -MP -MF $depbase.Tpo -c -o src/txrx-afpkt.o src/txrx-afpkt.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/txrx-afxdp.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.  -O2 -g -fstack-protector-strong -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wformat-overflow -Wno-parentheses -Wno-missing-field-initializers -Wextra -Wall -I/usr/local/include/open62541-iotg -I/usr/include/json-c     -g -O2 -MT src/txrx-afxdp.o -MD -MP -MF $depbase.Tpo -c -o src/txrx-afxdp.o src/txrx-afxdp.c &&\
mv -f $depbase.Tpo $depbase.Po
src/txrx-afxdp.c: In function ‘afxdp_send_pkt’:
src/txrx-afxdp.c:339:44: error: ‘struct xdp_desc’ has no member named ‘txtime’
  339 |  xsk_ring_prod__tx_desc(&xsk->tx_ring, idx)->txtime = tx_timestamp;
      |                                            ^~
src/txrx-afxdp.c: In function ‘afxdp_fwd_pkt’:
src/txrx-afxdp.c:620:48: error: ‘struct xdp_desc’ has no member named ‘txtime’
  620 |   xsk_ring_prod__tx_desc(&xsk->tx_ring, idx_tx)->txtime = tx_timestamp;
      |                                                ^~
make[1]: *** [Makefile:496: src/txrx-afxdp.o] Error 1
make[1]: Leaving directory '/home/user/iotg_tsn_ref_sw-master'
make: *** [Makefile:327: all] Error 2
```

**Comment by HomeLH** [comment]
```
/* Rx/Tx descriptor */
--
70 | struct xdp_desc {
71 | __u64 addr;
72 | __u32 len;
73 | __u32 options;
74 | };

```
https://github.com/intel/linux-intel-lts/blob/bf3bd966dfd7d9582f50e9bd08b15922197cd277/include/uapi/linux/if_xdp.h

**Comment by HomeLH** [comment]
https://github.com/intel/iotg-yocto-ese-main/blob/49159399331d2a71cff97863ea162a579faf08e0/recipes-connectivity/open62541/open62541-iotg/0007-feature-PubSub-Add-ETF-LaunchTime-support-for-XDP-tr.patch
> /* Note: txtime field is from a modified if_xdp.h xdp_desc struct
> +     * not available on upstream kernels yet.
> +     */

**Comment by vincentxw** [comment]
The xdp_desc txtime field is a yet-to-upstream kernel-level change. This means to use it, you need more than just add it at the library level.

As you've found, the top-level change is at the open62541 [library](https://github.com/intel/iotg-yocto-ese-main/blob/49159399331d2a71cff97863ea162a579faf08e0/recipes-connectivity/open62541/open62541-iotg/0007-feature-PubSub-Add-ETF-LaunchTime-support-for-XDP-tr.patch)

Next you'll need to ensure libbpf carries this struct change. Refer [here](https://github.com/intel/iotg-yocto-ese-main/blob/master/recipes-connectivity/libbpf/libbpf/0001-libbpf-add-txtime-field-in-xdp_desc-struct.patch)

Then, you should using a kernel with xdp txtime support. Refer to the [preempt-rt branch](https://github.com/intel/linux-intel-lts/blob/d5fde3d31ce39557fac848a476e3473b14f2c042/include/uapi/linux/if_xdp.h#L104)

Lets say you've booted into the kernel above, you should install the updated kernel headers into it so that you can compile libbpf and libopen62541 with txtime support on the platform.

But i found that not everyone uses the linux kernel headers as their c headers. In Yocto project's case, they use the linux-libc-headers instead. For prototyping, you can just modify the header files you're using, as we have done to our libc headers in [yocto](https://github.com/intel/iotg-yocto-ese-bsp/blob/master/recipes-kernel/linux-libc-headers/linux-libc-headers/0001-net-xdp-add-txtime-field-in-xdp_desc-in-header-file.patch)

**Comment by HomeLH** [comment]
@vincentxw Yeah, I modify the header files. It works. Thank you.

**Comment by pmlyanyuanyuan** [comment]
> I want to know how to compile the open62541-iotg package.

I want to know how to compile the open62541-iotg package too, my Ubuntu version is Ubuntu20.10，I met the same problem as you. Help me please.

**Comment by pmlyanyuanyuan** [comment]
> I build open62541-iotg through git patch, but I meet another build error..
> 
> ```
> 
> user@user-AIOT-AIVD:~/iotg_tsn_ref_sw-master$ ./build.sh
> configure.ac:3: installing './compile'
> configure.ac:2: installing './install-sh'
> configure.ac:2: installing './missing'
> Makefile.am: installing './depcomp'
> configure: WARNING: unrecognized options: --with-open62541-headers
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking whether make supports the include directive... yes (GNU style)
> checking dependency style of gcc... gcc3
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for libelf... yes
> checking for libbpf... yes
> checking for libjson... yes
> checking for open62451... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating config.h
> config.status: config.h is unchanged
> config.status: executing depfiles commands
> configure: WARNING: unrecognized options: --with-open62541-headers
> make  all-am
> make[1]: Entering directory '/home/user/iotg_tsn_ref_sw-master'
> depbase=`echo src/tsq.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
> gcc -DHAVE_CONFIG_H -I.  -O2 -g -fstack-protector-strong -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wformat-overflow -Wno-parentheses -Wno-missing-field-initializers -Wextra -Wall -I/usr/local/include/open62541-iotg -I/usr/include/json-c     -g -O2 -MT src/tsq.o -MD -MP -MF $depbase.Tpo -c -o src/tsq.o src/tsq.c &&\
> mv -f $depbase.Tpo $depbase.Po
> gcc  -g -O2 -Wl,-z,noexecstack,-z,relro,-z,now -pie  -o tsq src/tsq.o
> depbase=`echo src/txrx.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
> gcc -DHAVE_CONFIG_H -I.  -O2 -g -fstack-protector-strong -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wformat-overflow -Wno-parentheses -Wno-missing-field-initializers -Wextra -Wall -I/usr/local/include/open62541-iotg -I/usr/include/json-c     -g -O2 -MT src/txrx.o -MD -MP -MF $depbase.Tpo -c -o src/txrx.o src/txrx.c &&\
> mv -f $depbase.Tpo $depbase.Po
> depbase=`echo src/txrx-afpkt.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
> gcc -DHAVE_CONFIG_H -I.  -O2 -g -fstack-protector-strong -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wformat-overflow -Wno-parentheses -Wno-missing-field-initializers -Wextra -Wall -I/usr/local/include/open62541-iotg -I/usr/include/json-c     -g -O2 -MT src/txrx-afpkt.o -MD -MP -MF $depbase.Tpo -c -o src/txrx-afpkt.o src/txrx-afpkt.c &&\
> mv -f $depbase.Tpo $depbase.Po
> depbase=`echo src/txrx-afxdp.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
> gcc -DHAVE_CONFIG_H -I.  -O2 -g -fstack-protector-strong -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wformat-overflow -Wno-parentheses -Wno-missing-field-initializers -Wextra -Wall -I/usr/local/include/open62541-iotg -I/usr/include/json-c     -g -O2 -MT src/txrx-afxdp.o -MD -MP -MF $depbase.Tpo -c -o src/txrx-afxdp.o src/txrx-afxdp.c &&\
> mv -f $depbase.Tpo $depbase.Po
> src/txrx-afxdp.c: In function ‘afxdp_send_pkt’:
> src/txrx-afxdp.c:339:44: error: ‘struct xdp_desc’ has no member named ‘txtime’
>   339 |  xsk_ring_prod__tx_desc(&xsk->tx_ring, idx)->txtime = tx_timestamp;
>       |                                            ^~
> src/txrx-afxdp.c: In function ‘afxdp_fwd_pkt’:
> src/txrx-afxdp.c:620:48: error: ‘struct xdp_desc’ has no member named ‘txtime’
>   620 |   xsk_ring_prod__tx_desc(&xsk->tx_ring, idx_tx)->txtime = tx_timestamp;
>       |                                                ^~
> make[1]: *** [Makefile:496: src/txrx-afxdp.o] Error 1
> make[1]: Leaving directory '/home/user/iotg_tsn_ref_sw-master'
> make: *** [Makefile:327: all] Error 2
> ```

How patch? I met a problem 'unrecognization input'

**Comment by crow1814** [comment]
> @vincentxw Yeah, I modify the header files. It works. Thank you.

Hi, I have modified the header files in `/usr/src/linux-hwe-5.11-headers-5.11.0-27/include/uapi/linux/if_xdp.h.`,but I don't know how to make it work.

**Comment by GinoChen1218** [comment]
Temporary solution:
# vim /opt/intel/oneapi/tcc_tools/latest/scripts/install_host_dependencies.sh
=================================================
    git apply ${LIBBPF_PATCHES_PATH}/0001-libbpf-add-txtime-field-in-xdp_desc-struct.patch
    git apply ${LIBBPF_PATCHES_PATH}/0002-makefile-don-t-preserve-ownership-when-installing-fr.patch
    git apply ${LIBBPF_PATCHES_PATH}/0003-makefile-remove-check-for-reallocarray.patch
    read <== add this word "read"
    cd src/
=================================================
# sudo -E ./install_host_dependencies.sh
When executing read, the script pauses and go to modify if_xdp.h.

# vim /tmp/tmp.XXXXXXXXXX/libbpf/include/uapi/linux/if_xdp.h
=================================================
 	__u64 addr;
 	__u32 len;
 	__u32 options;
	__u64 txtime; <== add this line
=================================================
Complete the modification and continue to execute the script.

**Comment by crow1814** [comment]
I have installed all Dependencies, but I still encountered some problems `unknown type name` and `has no member named` when I execute the command `./build.sh.` The details are as follows

> mv -f $depbase.Tpo $depbase.Po
> depbase=echo src/opcua-tsn/opcua_datasource.o | sed 's|[^/]*$|.deps/&|;s|\.o$||';
> gcc -DHAVE_CONFIG_H -I. -O2 -g -fstack-protector-strong -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wformat-overflow -Wno-parentheses -Wno-missing-field-initializers -Wextra -Wall -fno-common -I/usr/local/include/open62541-iotg -I/usr/include/json-c -I/usr/local/include -I/usr/local/include -g -O2 -MT src/opcua-tsn/opcua_datasource.o -MD -MP -MF $depbase.Tpo -c -o src/opcua-tsn/opcua_datasource.o src/opcua-tsn/opcua_datasource.c &&
> mv -f $depbase.Tpo $depbase.Po
> In file included from src/opcua-tsn/multicallback_server.c:58:
> src/opcua-tsn/opcua_custom.h:70:5: error: unknown type name ‘UA_ReaderGroupConfig’
> 70 | UA_ReaderGroupConfig config;
> | ^~~~~~~~~~~~~~~~~~~~
> src/opcua-tsn/opcua_custom.h:107:5: error: unknown type name ‘UA_PubSubConnectionConfig’
> 107 | UA_PubSubConnectionConfig *config;
> | ^~~~~~~~~~~~~~~~~~~~~~~~~
> src/opcua-tsn/opcua_custom.h:109:5: error: unknown type name ‘UA_PubSubChannel’
> 109 | UA_PubSubChannel *channel;
> | ^~~~~~~~~~~~~~~~
> src/opcua-tsn/opcua_custom.h:126:5: error: unknown type name ‘UA_WriterGroupConfig’
> 126 | UA_WriterGroupConfig config;
> | ^~~~~~~~~~~~~~~~~~~~
> src/opcua-tsn/multicallback_server.c: In function ‘setupOpcuaServer’:
> src/opcua-tsn/multicallback_server.c:153:11: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayersSize’
> 153 | config->pubsubTransportLayersSize = 0;
> | ^~
> src/opcua-tsn/multicallback_server.c:154:11: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayers’
> 154 | config->pubsubTransportLayers =
> | ^~
> src/opcua-tsn/multicallback_server.c:155:35: error: expected expression before ‘)’ token
> 155 | (UA_PubSubTransportLayer *) UA_calloc(2, sizeof(UA_PubSubTransportLayer));
> | ^
> In file included from src/opcua-tsn/opcua_common.h:44,
> from src/opcua-tsn/multicallback_server.c:55:
> src/opcua-tsn/multicallback_server.c:156:21: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayers’
> 156 | catch_err(config->pubsubTransportLayers == NULL, "Out of memory");
> | ^~
> src/opcua-tsn/opcua_utils.h:50:13: note: in definition of macro ‘catch_err’
> 50 | if (A) {
> | ^
> src/opcua-tsn/multicallback_server.c:159:15: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayers’
> 159 | config->pubsubTransportLayers[0] = UA_PubSubTransportLayerEthernetXDP();
> | ^~
> src/opcua-tsn/multicallback_server.c:161:15: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayers’
> 161 | config->pubsubTransportLayers[0] = UA_PubSubTransportLayerEthernetETF();
> | ^~
> src/opcua-tsn/multicallback_server.c:163:11: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayersSize’
> 163 | config->pubsubTransportLayersSize++;
> | ^~
> src/opcua-tsn/multicallback_server.c:187:19: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayers’
> 187 | config->pubsubTransportLayers[1] = UA_PubSubTransportLayerEthernetXDP();
> | ^~
> src/opcua-tsn/multicallback_server.c:188:19: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayersSize’
> 188 | config->pubsubTransportLayersSize++;
> | ^~
> src/opcua-tsn/multicallback_server.c:192:19: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayers’
> 192 | config->pubsubTransportLayers[1] = UA_PubSubTransportLayerEthernetETF();
> | ^~
> src/opcua-tsn/multicallback_server.c:193:19: error: ‘UA_ServerConfig’ {aka ‘struct UA_ServerConfig’} has no member named ‘pubsubTransportLayersSize’
> 193 | config->pubsubTransportLayersSize++;
> | ^~
> make[1]: *** [Makefile:496：src/opcua-tsn/multicallback_server.o] 错误 1
> make[1]: *** 正在等待未完成的任务....
> In file included from src/opcua-tsn/opcua_custom.c:46:
> src/opcua-tsn/opcua_custom.h:70:5: error: unknown type name ‘UA_ReaderGroupConfig’
> 70 | UA_ReaderGroupConfig config;
> | ^~~~~~~~~~~~~~~~~~~~
> src/opcua-tsn/opcua_custom.h:107:5: error: unknown type name ‘UA_PubSubConnectionConfig’
> 107 | UA_PubSubConnectionConfig *config;
> | ^~~~~~~~~~~~~~~~~~~~~~~~~
> src/opcua-tsn/opcua_custom.h:109:5: error: unknown type name ‘UA_PubSubChannel’
> 109 | UA_PubSubChannel *channel;
> | ^~~~~~~~~~~~~~~~
> src/opcua-tsn/opcua_custom.h:126:5: error: unknown type name ‘UA_WriterGroupConfig’
> 126 | UA_WriterGroupConfig config;
> | ^~~~~~~~~~~~~~~~~~~~
> src/opcua-tsn/opcua_custom.c: In function ‘pub_thread’:
> src/opcua-tsn/opcua_custom.c:179:31: error: request for member ‘transportSettings’ in something not a structure or union
> 179 | currentWriterGroup->config.transportSettings = transportSettings;
> | ^
> make[1]: *** [Makefile:496：src/opcua-tsn/opcua_custom.o] 错误 1
> make[1]: 离开目录“/home/lab640/gmj/iotg_tsn_ref_sw”
> make: *** [Makefile:327：all] 错误 2
