### ISSUE TITLE
Problem with Instructions for Building BSP for Apollo Lake

### ISSUE THREAD

**Issue by jalopy8** [intel/iotg_tsn_ref_sw#2]
Hello,
 
I am trying to build the Apollo Lake BSP, and the instructions seem to be wrong. I am referring to iotg_tsn_ref_sw-userguide-20190131/TSN_UG/index.htm, section Step 1: Prepare the Host Machine and Build the BSP. I have successfully setup the host build machine, cloned the iotg-yocto-bsp-public git repo, and ran the setup.sh script.
There seems to be two problems with the instructions in this section:
There is no E3900-MR4-PREEMPT-RT branch/tag to checkout
The line, "When prompted to build a custom image, select core-image-rt-tsn-sdk." We do not get prompted to "build a custom image," and when setup.sh does present targets, "core-image-rt-tsn-sdk" is not included in the list.
 
Thanks,

-Jack

**Comment by vincentxw** [comment]
Hi, 

The name of the BSP tag changed prior to the release. We've updated this in our documentation in a very recent commit. The BSP tag you should be checking out is MR4rt-B-01. Once you've checked that out, the build steps should be similar to the UG.

Thanks!
