### ISSUE TITLE
sendmsg failed - 105: No buffer space available

### ISSUE THREAD

**Issue by TausR** [intel/iotg_tsn_ref_sw#3]
Hi.

I am trying to recreate some the sample-app-taprio setup from demo 3 scenario 3. However, I am experiencing a sendmsg error in the udp_send function: 105: No buffer space available. I am using ubuntu 18.04 with mainline kernel 4.20.17.

When this error occurs the application stops transmitting any other data than priority 5 using tsn_prio5-s1s2s3, tsn_prio3-s1s2s3 for the application configuration. 

Do you have any idea why this error occurs? Also let me know if I should provide additional information.

Regards.

Taus

**Comment by vincentxw** [comment]
Hi there,

For these set of applications, we developed and tested using a Yocto BSP which uses a specific [Intel preempt-rt production kernel](https://github.com/intel/linux-intel-lts/tree/4.14/preempt-rt). This kernel carries some backported patches from ~5.1 mainline kernel. I'd recommend using this kernel , though i understand that may not be possible for every one. The patches we backported were primarily for the ETF and TAPRIO qdisc.

For this specific error, i think it would be the ETF patches that might be missing in your kernel. You may take a look [here](https://github.com/intel/linux-intel-lts/commits/4.14/preempt-rt/net/sched/sch_etf.c) and see if your existing kernel has all the appropriate commits.
