### ISSUE TITLE
What is the matching open62541 commit to match with master

### ISSUE THREAD

**Issue by darshanraj-ka** [intel/iotg_tsn_ref_sw#4]
Hello, What is the matching 'https://github.com/open62541/open62541.git' commit to use?
I have generated amalgamated open62541.h from open62541/master branch 
(commit 6427010002a44a927dd2ba22b51acf8d31659329)

while building **master** branch here, I see this error -> 

**git/iotg_tsn_ref_sw/sample-app-opcua-pubsub/tutorial_pubsub_publish_sotxtime.c:137:21: error: \u2018UA_PubSubConnectionConfig {aka struct <anonymous>}\u2019 has no member named \u2018sockPrio\u2019
     connectionConfig.sockPrio = SOCKET_PRIORITY;**

**Comment by darshanraj-ka** [comment]
Another incompatibility noticed - 

sample-app-1.c:160:22: error: too many arguments to function 'UA_Server_new'
  UA_Server *server = UA_Server_new(config);
                      ^~~~~~~~~~~~~
In file included from sample-app-1.c:64:0:
/usr/local/include/open62541.h:23911:23: note: declared here
 UA_Server UA_EXPORT * UA_Server_new(void);
                       ^~~~~~~~~~~~~

**Comment by vincentxw** [comment]
Hi, We are using a custom open62541 version in the BSP. Its listed in the dependencies doc. If you take a look at the [recipe](https://github.com/intel/iotg-yocto-bsp-public/tree/MR4rt-B-01/meta-intel-tsn/recipes-connectivity/open62541/), it lists the specific commit we checked out and applied our own patches on it.
