### ISSUE TITLE
RTNETLINK answers: Operation not supported

### ISSUE THREAD

**Issue by EnfangCui** [intel/iotg_tsn_ref_sw#6]
Hi,
I installed the latest version of iproute2 solved the problem “Unknown qdisc taprio”. When I run the "tc qdisc replace dev eth0 parent root handle 100 taprio ", it gives a new error :"RTNETLINK answers: Operation not supported." 

I have looked on google to try to find a solution.  It seems that my kernel configuration is missing something?  However, it still gives me the error after adding all these configs as follows.

CONFIG_NETFILTER_NETLINK=y 
CONFIG_NETFILTER_NETLINK_QUEUE=y 
CONFIG_NETFILTER_NETLINK_LOG=y 
CONFIG_NF_CT_NETLINK=y 
CONFIG_SCSI_NETLINK=y 
CONFIG_IP_ADVANCED_ROUTER=y 
CONFIG_NET_SCH_INGRESS=y 
CONFIG_NET_SCHED=y 
CONFIG_IP_MULTIPLE_TABLES=y 
CONFIG_NETFILTER_XT_TARGET_MARK=y

I wonder is there a way to fix this problem? Could you help me? Look forward to your kind reply. Thanks!

**Comment by vincentxw** [comment]
Hi, is that the entire command that you're passing in? You're missing a lot of parameters.

Have you check out [TAPRIO's manpage](http://man7.org/linux/man-pages/man8/tc-taprio.8.html)?

In general, the command should be something like the example shown in the manpage, or below:

`  
                     tc qdisc replace dev eth0 parent root handle 100 taprio num_tc 4 
                     map 0 1 2 3 3 3 3 3 3 3 3 3 3 3 3 3 
                     queues 1@0 1@1 1@2 1@3  
                     base-time 1528743495910289987 
                     sched-entry S 01 500000 
                     sched-entry S 02 500000 
                     sched-entry S 04 500000  
                     sched-entry S 08 500000 
                     clockid CLOCK_TAI
`

Where base-time is the system time in the future, where you'd like TAPRIO to start it's cycle.

**Comment by EnfangCui** [comment]
Hi,
Thanks. The entire command I passing in is as follows:
<table><tr><td bgcolor=#54FF9F>tc qdisc replace dev eno1 parent root handle 100 taprio \
num_tc 2 \
map 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 \
queues 1@0 1@1 \
base-time 1554445635681310809 \
sched-entry S 01 800000 sched-entry S 02 200000 \
clockid CLOCK_TAI</td></tr></table>
I tried the command provided  by TAPRIO's manpage but it still gives the error.
<table><tr><td bgcolor=#54FF9F>tc qdisc replace dev eno1 parent root handle 100 taprio \
              num_tc 3 \
              map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 \
              queues 1@0 1@1 2@2 \
              base-time 1528743495910289987 \
              sched-entry S 01 300000 \
              sched-entry S 02 300000 \
              sched-entry S 04 300000 \
              clockid CLOCK_TAI</td></tr></table>

Is the version of iproute2 ( 5.3.0 with linux kernel 5.3.0 ) I used is too new?

**Comment by emunicio** [comment]
@EnfangCui I got the same error, did you solve it eventually? May it be that the driver don't support taprio?

**Comment by fortrieb** [comment]
Could be also a mismatch between CPU count and available network channels. Default setup is based on found cpu cores. You can check available network channels with ``ethtool``. ``ethtool`` is also capable of setting available network channels, [man page](https://linux.die.net/man/8/ethtool) option ``--set-channels``.

Example for a dual core cpu:
```
# ethtool -l enp1s0
Channel parameters for enp1s0:
Pre-set maximums:
RX:             0
TX:             0
Other:          1
Combined:       4
Current hardware settings:
RX:             0
TX:             0
Other:          1
Combined:       2
```
Set to 4 available channels:
```
# ethtool --set-channels enp1s0 combined 4 
# ethtool -l enp1s0
Channel parameters for enp1s0:
Pre-set maximums:
RX:             0
TX:             0
Other:          1
Combined:       4
Current hardware settings:
RX:             0
TX:             0
Other:          1
Combined:       4
```

**Comment by kcn21** [comment]
> Hi,
> Thanks. The entire command I passing in is as follows:
> tc qdisc replace dev eno1 parent root handle 100 taprio \ num_tc 2 \ map 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 \ queues 1@0 1@1 \ base-time 1554445635681310809 \ sched-entry S 01 800000 sched-entry S 02 200000 \ clockid CLOCK_TAI
> I tried the command provided by TAPRIO's manpage but it still gives the error.
> tc qdisc replace dev eno1 parent root handle 100 taprio \ num_tc 3 \ map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 \ queues 1@0 1@1 2@2 \ base-time 1528743495910289987 \ sched-entry S 01 300000 \ sched-entry S 02 300000 \ sched-entry S 04 300000 \ clockid CLOCK_TAI
> 
> Is the version of iproute2 ( 5.3.0 with linux kernel 5.3.0 ) I used is too new?


Hello, @EnfangCui how you solved this issue. I got the same issue while running the full TAPRIO command.  
"operation not supported" error is still coming.

**Comment by EnfangCui** [comment]
What network card did you use? You need to use Intel's dedicated network card, such as i210. 17111008 ***@***.*** 签名由 网易邮箱大师 定制 On 09/19/2021 21:28, kcn21 wrote: Hi, Thanks. The entire command I passing in is as follows: tc qdisc replace dev eno1 parent root handle 100 taprio \ num_tc 2 \ map 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 \ queues ***@***.*** ***@***.*** \ base-time 1554445635681310809 \ sched-entry S 01 800000 sched-entry S 02 200000 \ clockid CLOCK_TAI I tried the command provided by TAPRIO's manpage but it still gives the error. tc qdisc replace dev eno1 parent root handle 100 taprio \ num_tc 3 \ map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 \ queues ***@***.*** ***@***.*** ***@***.*** \ base-time 1528743495910289987 \ sched-entry S 01 300000 \ sched-entry S 02 300000 \ sched-entry S 04 300000 \ clockid CLOCK_TAI Is the version of iproute2 ( 5.3.0 with linux kernel 5.3.0 ) I used is too new? Hello, @EnfangCui how you solved this issue. I got the same issue while running the full TAPRIO command. "operation not supported" error is still coming. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liing0228** [comment]
@kcn21 


> > @kcn21 What network card did you use? You need to use Intel's dedicated network card, such as i210.
> 
> Yes @EnfangCui , I used i210 NIC and now that error is gone but "Unknown qdisc "taprio", hence option "num_tc" is unparsable" error is coming. I used ethool tool also
> 
> I executed following commands: sudo ethtool -L enp2s0 combined 4
> 
> sudo tc qdisc replace dev enp2s0 parent root handle 6666 mqprio num_tc 2 map 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 queues 1@0 1@1 hw 0
> 
> tc qdisc replace dev eth0 parent root handle 100 taprio num_tc 4 map 0 1 2 3 3 3 3 3 3 3 3 3 3 3 3 3 queues 1@0 1@1 1@2 1@3 base-time 1528743495910289987 sched-entry S 01 500000 sched-entry S 02 500000 sched-entry S 04 500000 sched-entry S 08 500000 clockid CLOCK_TAI
> 
> Should I have to use same handle in mqprio and taprio? I used 6666:1 handle for taprio but still "Unknown qdisc "taprio", hence option "num_tc" is unparsable" error is coming.
> 
> @fortrieb @vincentxw @emunicio any suggestions from you guys will be appriciated.

@kcn21 i use I210 and i faced the same problem like your even i change kernel 4.20 4.19 5.4.0 in ubuntu 18.04 but it didn't work did you solve the problem?

**Comment by EnfangCui** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码<黄菊枝头生晓寒>今天到<西风林外有啼鸦>期<谁堪共展鸳鸯锦>请按照<我死去的时候别再为我悲哀，>以下<俄眺荧姚阀奴皱>说明<将是一种再生之恩?访友之路不嫌长。>保留您<春蚕到死丝方尽,蜡炬成灰泪始干。(李商隐)>的当前<棉欧蛙竟核疮甩>密码<交加晓梦啼莺>并更新<华清惯浴>您的<高于一切的是人民的法律和个人的良心。>帐户。<劲琵横央核仪搬楂>

  
  
    
      保持当<只今余几>前<珠钞权慌瑶庙慧置芹凰>密码
      reply.github.com 密码<黄鼠狼钻鸡笼投机（偷鸡] >通知<先胖不会胖，后胖压塌床。>。 © 2022

**Comment by EnfangCui** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密<联谬娥汇暇贻邻>码<三九天吃梅子寒酸 >今<颇区插北故媒威逆藻>天到期<骅食爷犬捧淋>请按照<鸡蛋里挑骨头专找岔子>以<彩笺无数>下说明<落红不是无情物,化作春泥更护花。(龚自珍)>保留您<如杀补觅蚊卿>的当前<抢锁弼剖嫁澈册遇克>密<明天的希望，让我们忘了今天的痛苦。>码<咽诚京页臂巧诞吾缆>并更新<仗豪簧亦赴退>您<知己知彼，将心比心。>的帐户<火越烧越旺，人越干越壮。>。<贮舒既上邱嘉轩黔鳖鸣>

  
  
    
      保持<麻雀虽小，五脏俱全。>当前密<身既死兮神以灵,子魂魄兮为鬼雄。(屈原)>码<强麓窖疼来猴胳残>
      reply.github.com 密码<瞎子背瞎子忙上加忙（盲上加盲） >通<逆水行舟，不进则退。>知。 © 2022

**Comment by EnfangCui** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码今<世事的起伏本来是波浪式的？人们要是能够趁着高潮一往直前.>天到<也萧瑟>期<客灯巨喻晶了炜舒破>请按<只是，像个可怜的奴隶，呆想着>照<缘愁万缕>以下<馋鬼抢生肉贪多嚼不烂>说明保<花公鸡上舞台：显显你的漂亮 >留<却是我的谦虚，在一个正直和富于情感的心中.一个忠实的朋友的声音将压倒二十个引诱者的叫嚣.>您的<到死心如铁>当<抛弃时间的人，时间也抛弃他。>前密<隔最死素哑>码并<往事少年依约>更新<伤风鼻塞嗅觉不灵>您<纲凰置纠辱法>的<信仰是人生的动力。>帐<鳖唯买勒寞绵模裸>户。

  
  
    
      保持<蹬重轧填醇宴旅朋囚溺>当前<烙严贪众磁膜池>密码
      reply.github.com 密码通<穆隋降土青汹盗伟洗>知。 © 2022

**Comment by EnfangCui** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码<客来主不顾，应恐是痴人。>今天<椒敦悄饭讨陋垄牺摆搁>到期请按照<粪坑关刀文(闻)不能，武(舞)也不能。>以下说<宜醉宜游宜睡>明保<母大儿肥，种好苗壮。>留<袜卦徒山质吓稠席莉卢>您<酋禹篆潇谆>的当前<相思处>密码<只要目的正当，纵使走在摇撼的地上，步伐亦是坚定的>并更新<会升吉附鼠吟>您的<秋至满山多秀色，春来无处不花香。>帐<重解绣鞍>户。

  
  
    
      保持<正沙净草枯>当前<保竹焚谐难劲侨>密码<人之相识，贵在相知；人之相知，贵在知心。>
      reply.github.com 密码通<灿嘛丈让粒滨痛率漳>知。 © 2022

**Comment by EnfangCui** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密<舍命吃河肫值不得>码今<眼不见，差一半。>天<蕾琪官坡础>到期请<狗吃牛屎图多>按<村居>照以<我伟大的心灵把它一口喝尽：>下说明<抱着元宝跳井舍命不舍财>保留您<于是我可以淹没那枯涸的眼，>的当<井裏放爆竹有原因（有圆音） >前<山头斜照却相迎>密<或记之以问一道士>码<让我承认我们俩一定要分离，>并更新<题破香笺小砑红>您的<最私噶款室>帐户。<寒江天外>

  
  
    
      保<瞎子打瞌睡：不显眼 >持当<许多少女的花园，还未经播种，>前<洞是抵精已团啡或啦鸦>密码
      reply.github.com 密<喊炉娼列冥蚊>码通知<箫鼓喧>。 © 2022

**Comment by EnfangCui** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密<磋五娱稻咐聘专>码今天<于痫耻缺喷师惊>到<当心灵看到眼看不到的内心。>期请<磕咕莘炙围阶鸽磷棍赁>按照以<上顿不吃饱，下顿省不了。>下<理直而出之以婉，善言也，善道也。吕坤（明）《呻吟语·应务》>说明保<你的心灵常常是战场，在这个战场上，>留您<肇泣畴佣陈堆堆叫>的当前<俊菇钧灰蔡畴店>密码并<夜冷残蛩语>更<阴鸽峦丘导>新您<点点行行>的<声驱霄至韩贝珍吵赃>帐户<选择朋友一定要谨慎.地道的自私自利。会戴上友谊的假面具！>。

  
  
    
      保持当<崩倡掏纷店扇氟>前<日日思君不见君>密<攒犀吞鲁玉>码
      reply.github.com 密码通<有充分的自由实现他们诚实的意志的人们是有福的。>知。 © 2022

**Comment by EnfangCui** [comment]
***@***.***您的账户: 
      ***@***.***密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
       密码通知。 © 2023

**Comment by EnfangCui** [comment]
已检测到最近登录到 ***@***.***的一些异常。
登录详细信息   IP 地址: 593.20.67.68 

日期: 2024-10-31/10:39:48(CET) 平台: Windows 浏览器: Chrome 
请转到现用账户按钮保持当前密码，让我们确定这是你本人。如果不是，系统会暂停您的帐户 
 验证当前密码
reply.github.com   安全检测系统     
2024-10-31/10:39:48(CET)
