### ISSUE TITLE
Qav simple-talker-cmsg transmits too many packets.

### ISSUE THREAD

**Issue by TausR** [intel/iotg_tsn_ref_sw#7]
Hi,

I'm trying to follow the demos provided in the documentation, more specifically "Qav Demo 2 Scenario 2 ", but when the simple-talker-cmsg is activated, it transmits 900,000 packets/s instead of 8000 packets/s as in the example. 

What settings determine the transfer rate of the simple-talker-cmsg?
What do you believe causes this problem? 

Regards.

Taus

**Comment by vincentxw** [comment]
Hi, 

The CBS qdisc is the one that moderates the transmission speed.  You can check your qdisc settings with "tc qdisc show dev eth0"

In this project, this is set within the [app](https://github.com/intel/iotg_tsn_ref_sw/blob/apollolake-i/simple-talker-cmsg/simple-talker-cmsg.c#L509). Which is just running the tc command in C. You can also do it in shell/bash using the [tc command](http://man7.org/linux/man-pages/man8/tc-cbs.8.html)

**Comment by TausR** [comment]
Hi, 

You are correct in the origin of the error, i have narrowed it down to the "offload"  parameter. When i try and run the tc command with the "offload" set to 1 it returns this error. 

"tc qdisc replace dev enp4s0 parent 100:1 cbs idleslope 7808 sendslope -992192 hicredit 12 locredit -97 offload 1"

"RTNETLINK answers: Operation not supported"

I can run the same command with the "offload" set to 0, but this results in a lack of trafik shaping. 

I am using a i210 NIC that is running the igb_AVB driver from openAVnu, if that helps.

**Comment by aguedes** [comment]
Hi @TausR, igb_avb driver is not compatible with cbs qdisc. You should be using the igb driver from the Linux kernel mainline.

**Comment by TausR** [comment]
Thank you @aguedes  and @vincentxw for you help, i changed the driver back to igb and it fixed the problem.
